album/urls.py
from django.urls import path, include
from album import views

urlpatterns = [
    path('', views.base, name='base'),
    path('category', views.category, name='category-list'),
    path('category/detail<int:category_id>/', views.category_detail, name='category-detail'),
    path('photo', views.PhotoListView.as_view(), name='photo-list'),
    path('photo/detail<int:pk>/', views.PhotoDetailView.as_view(), name='photo-detail'),
    path('photo/update<int:pk>/', views.PhotoUpdate.as_view(), name='photo-update'),
    path('photo/create', views.PhotoCreate.as_view(), name='photo-create'),
    path('photo/delete<int:pk>/', views.PhotoDelete.as_view(), name='photo-delete'),
]

myapps/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('album/', include('album.urls')),
    path('admin/', admin.site.urls),
]

album/models.py
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver

# Create your models here.

class Category(models.Model):
    """Categorías para clasificar las fotos"""
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Photo(models.Model):
    """Fotos del album """
    category = models.ForeignKey(Category, null=True, blank = True, on_delete=models.PROTECT)
    title = models.CharField(max_length=50, default='No title')
    photo = models.ImageField(upload_to='photos/')
    pub_date = models.DateField(auto_now_add=True)
    favorite = models.BooleanField(default=False)
    comment = models.CharField(max_length=200, blank= True)

    def __str__(self):
        return self.title
        
    def get_absolute_url(self):
        return reverse('photo-list')

@receiver(post_delete, sender=Photo)
def photo_delete(sender, instance, **kwargs):
    """Borra los ficheros de las fotos que se eliminan. """
    instance.photo.delete(False)

album/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from album.models import Category, Photo
from django.views.generic import ListView, DetailView 
from django.urls import reverse_lazy
from django.views.generic.edit import UpdateView, CreateView, DeleteView 

# Create your views here.

def first_view(request):
    return HttpResponse('Esta es mi primera vista!')

def category(request):
    category_list = Category.objects.all()
    context = {'object_list': category_list}
    return render(request, 'album/category.html', context)

def category_detail(request, category_id):
    category = Category.objects.get(id=category_id)
    context = {'object': category}
    return render(request, 'album/category_detail.html', context)

def base(request):
	return render(request, 'base.html')

class PhotoListView(ListView):
    model = Photo
class PhotoDetailView(DetailView):
    model = Photo

    '''def get_object(self):
        return get_object_or_404(Category, pk=request.session['user_id'])'''

class PhotoUpdate(UpdateView):
    model = Photo
    fields = '__all__'

class PhotoCreate(CreateView):
    model = Photo
    fields = '__all__'

class PhotoDelete(DeleteView):
    model = Photo
    fields = '__all__'
    success_url = reverse_lazy('photo-list')

album/templates/album/category.html
{% extends 'base.html' %}

{% block section %}

<h2>Category</h2>
<hr>

{% endblock section %}

{% block maincontent %}

<div>
	{% for c in object_list %}
		<a href="{% url 'category-detail' c.pk %}" title=""> 
			{{c.name}}
		</a>
	{% endfor %}
</div>
{% endblock maincontent %}

album/templates/album/category_detail.html
{% extends 'base.html' %}
{% load static %}
{% block section %}
 <h2>{{ object.name }}</h2>
 <hr>
{% endblock section %}
{% block maincontent %}
<div>
 <table border="1px">
 <tr>
 {% for p in object.photo_set.all %}
 <td>
 <div>{{ p.title }}</div>
 <div>
 <a href="{% url 'photo-detail' p.id %}">
 <img src="{% static p.photo.url %}"
style="width:200px;height:200px"/>
 </a>
 </div>
 </td>
 {% endfor %}
 </tr>
 </table>
</div>
{% endblock maincontent %}

album/templates/album/photo_confirm_delete.html
{% extends 'base.html' %}

{% block maincontent %}
 <form action=""method="post">
     {% csrf_token %}
 <p>Delete "{{ object.title }}"?</p>
 <input type="submit"value="Confirm" />
 <a class='btn'href="{% url 'photo-list' %}">Cancel</a>
 </form>
{% endblock maincontent %} 

album/templates/album/photo_detail.html
{% extends 'base.html' %}
{% load static %}
{% block section %}
	<h2>
		{{ object.title }}
		{% if object.favorite %}
 			&#9733;
 		{% else %}
 			&#9734;
 		{% endif %}
 		{% if object.category_id %}
 			( <a href="{% url 'category-detail' object.category_id %}">{{ object.category }}</a> )
 		{% endif %}
 	</h2>
 	<p><strong>comments: </strong>{{ object.comment|default:"no comments" }}</p>
 	<a href="{% url 'photo-update' object.id %}">edit</a>
 	<a href="{% url 'photo-delete' object.id %}">delete</a>
 	<hr>
{% endblock section %}
{% block maincontent %}
<div>
	<div>
 		<img src="{% static object.photo.url %}" style="width:550px;height:420px"/>
 	</div>
</div>
{% endblock maincontent %} 

album/templates/album/photo_form.html
{% extends "base.html" %}
{% block maincontent %}
 <form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ form.as_p }}
 <button type="submit">Save</button>
 <a class='btn' href="{% url 'photo-list' %}">Cancel</a>
 </form>
{% endblock maincontent%} 

album/templates/album/photo_list.html
{% extends 'base.html' %}
{% load static %}
{% block section %}
 <h2>Photo</h2> 
 <hr>
{% endblock section %}
{% block maincontent %}
 <div class="row well">
 {% for p in object_list.all %}
 <div class="col-md-4 well">
 <div class="panel panel-primary">
 <div class="panel-heading">
 <h3 class="panel-title">{{ p.title }}</h3>
 </div>
 <div class="panel-body">
 <a href="{% url 'photo-detail' p.id %}">
 <img src="{% static p.photo.url %}" style="width:200px;height:200px;"/>
 </a>
 </div>
 <div class="panel-footer">
 {% if p.comment %}
 {{ p.comment }}
 {% else %}
 <a href="{% url 'photo-update' p.id %}">edit comments</a>
 {% endif %}
 </div>
 </div>
 </div>
 {% endfor %}
 </div>
{% endblock maincontent %} 

album/templates/base.html
<!DOCTYPE html>
<html>
<head lang="en">
 <meta charset="UTF-8">
 <title>Album</title>
 <!-- CDN Bootstrap -->
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
</head>
<body>
 <!-- NavBar -->
 <nav class="navbar navbar-default">
 <div class="container-fluid">
 <div class="navbar-header">
 <button type="button"class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
 <span class="sr-only">Toggle navigation</span>
 <span class="icon-bar"></span>
 <span class="icon-bar"></span>
 <span class="icon-bar"></span>
 </button>
 <a class="navbar-brand"href="{% url 'base' %}">Album</a>
 </div> 
 <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
 <ul class="nav navbar-nav">
 <li><a href="{% url 'category-list' %}">Category<span class="sr-only">(current)</span></a></li>
 <li><a href="{% url 'photo-list' %}">Photo</a></li>
 </ul>
 <ul class="nav navbar-nav navbar-right">
 <li class="dropdown">
 <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Action <span class="caret"></span>
 </a>
 <ul class="dropdown-menu" role="menu">
 <li><a href="{% url 'photo-create' %}">Upload</a></li>
 <li class="divider"></li>
 <li><a href="#">Log In</a></li>
 </ul>
 </li>
 </ul>
 </div>
 </div>
 </nav>
 <div class="container">
 {% block section %}
 {% endblock section %}
 </div>
 <div class="container">
 {% block maincontent %}
 {% endblock maincontent %}
 </div>
</body>
</html>